### ISSUE TITLE
Suport Grouping

### ISSUE THREAD

**Issue by lmorillas** [TheWatcher/InteractiveTimeline#3]
Is it possible to group events with itimeline like this chap example? http://almende.github.io/chap-links-library/js/timeline/examples/example13_grouping.html

**Comment by TheWatcher** [comment]
It's not currently supported, but I'll have a look at what'd need to be added to do it later today.

**Comment by lmorillas** [comment]
I think we can consider  count( $parts ) == 2  and  count( $parts ) == 3 at 
https://github.com/TheWatcher/InteractiveTimeline/blob/master/InteractiveTimeline.body.php#L305

**Comment by TheWatcher** [comment]
My apologies for the delay with this; life got hectic. Version 1.4 (730c469e18d4e8976a3aefc63794c0850863918a) is now available with grouping support - I have turned on the 'groupsonright', 'groupswidth', and 'groupsminheight' configuration parameters, and extended the event syntax to include the option to specify a group name. I have not enabled the 'groupsChangeable' or 'groupsOrder' options - the former because it makes no sense, and the latter because it would mean dealing with javascript insertion headaches I'd rather steer clear of.

Please see [the extension page](https://www.mediawiki.org/wiki/Extension:InteractiveTimeline) for the updated [configuration options](https://www.mediawiki.org/wiki/Extension:InteractiveTimeline#Parameters) and [event syntax](https://www.mediawiki.org/wiki/Extension:InteractiveTimeline#Event_Syntax)

Please tell me if it does what you need.

**Comment by lmorillas** [comment]
Thanks Chris, It's working fine now with groups.
